services:

    voileux.persona.authentication.listener:
        class: Voileux\PersonaBundle\Security\Firewall\PersonaListener
        arguments:
            - @security.context
            - @voileux.persona.authentication.provider
            - %persona.verifier_url%
            - @buzz

    voileux.persona.authentication.provider:
        class: Voileux\PersonaBundle\Security\Authentication\Provider\PersonaProvider
        arguments:
            - @security.context
            - %persona.user_provider%
            - %persona.verifier_url%
            - @buzz