parameters:
    persona.verifier_url: 'https://verifier.login.persona.org/verify'
    persona.audience_url: 'http://example.com'

services:
    voileux.persona.authentication.listener:
        class: Voileux\PersonaBundle\Security\Firewall\PersonaListener
        arguments:
            - @security.context
            - @voileux.persona.authentication.provider

    voileux.persona.authentication.provider:
        class: Voileux\PersonaBundle\Security\Authentication\Provider\PersonaProvider
        arguments:
            - @voileux.core.user.manager
            - true
            - %persona.verifier_url%
            - %persona.audience_url%
            - @buzz
