parameters:
    voileux.admin.email: 'info@lesvoileux.com'
    mailer_transport:  smtp
    mailer_host:       in.mailjet.com
    mailer_user:       68327b485d1cefa7e1426a7597063e58
    mailer_password:   ecd45d17f21c6171958c27a544b31c1a
    mailer_port: 587

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }


framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"

    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~



# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - VoileuxWebBundle
    java: /usr/bin/java
    filters:
        coffee:
            apply_to:   "\.coffee$"
            node:       %node_bin%
            bin:        %coffee_bin%
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/closure-compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yui-compressor.jar"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:  "%mailer_port%"
    spool:     { type: memory }


fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Voileux\CoreBundle\Entity\User




jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs, test, Tests]
            domains: [messages, validators, validator]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

    title:      Les Voileux Admin

    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true


avalanche_imagine:
    source_root:  %kernel.root_dir%/../web
    web_root:     %kernel.root_dir%/../web
    cache_prefix: media/cache
    driver:       gd

    filters:
        user_index:
            type: chain
            options:
                filters:
                    relative_resize:
                        widen: 80
                    crop:
                        start: [0, 0]
                        size: [80, 80]
        boat_index:
            type: chain
            options:
                filters:
                    relative_resize:
                        widen: 1920
                    crop:
                        start: [0, 0]
                        size: [1920, 700]

        user_main:
            type: chain
            options:
                filters:
                    relative_resize:
                        widen: 400
                    crop:
                        start: [0, 0]
                        size: [400, 400]

        boat_details:
            type: chain
            options:
                filters:
                    relative_resize:
                        widen: 687
