parameters:

    node_bin: /usr/local/bin/node
    coffee_bin: /usr/local/bin/coffee
    less_bin: /usr/local/bin/lessc
    assetic.filter.less.node: /usr/local/bin/node
    assetic.filter.less.node_paths:
        - /usr/local/lib/node_modules

    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     voileux
    database_user:     root
    database_password: z0bilam0uche

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    work.related.number: 5
    index.works.per_page: 20