jms_security_extra:
    secure_all_services: false
    expressions: true


security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_PRIVATE:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_PRIVATE, ROLE_TRANSLATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PRIVATE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        fos_user.user_provider:
            id: fos_user.user_provider.username
        voileux.user_manager:
            id: voileux.core.user.manager

    firewalls:

        persona_secured:
            pattern: ^/
            persona: true
            provider: voileux.user_manager
            logout:    true
            anonymous:    true

        main:
            provider: fos_user.user_provider.username
            pattern: ^/
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/boat/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }

