<?php

namespace Voileux\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoatRepository extends EntityRepository
{
}
